version: 0.2

env:
  variables:
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - cd app1-ai-chatbot
      - docker build -t ai-chatbot:$IMAGE_TAG .
      - docker tag ai-chatbot:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ai-chatbot:$IMAGE_TAG

  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ai-chatbot:$IMAGE_TAG
      - echo "IMAGE PUSHED SUCCESSFULLY"
